import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Icon } from "../../components/icon";
import { DOWNLOADS, RELEASE_VERSION, REPOSITORY_URL } from "../../lib/site";

export const metadata: Metadata = {
  title: "Your first session — Getting started",
  description: "Set up Assistive Control on Windows, allow camera access, calibrate your movements, customize your mapping, and learn how to pause or stop control.",
};

const sections = [
  ["before-you-start", "Before you start"], ["install", "1. Choose your download"],
  ["camera", "2. Set up your camera"], ["calibrate", "3. Find your movements"],
  ["personalize", "4. Review your controls"], ["start-control", "5. Start, pause, and stop"],
  ["troubleshooting", "Troubleshooting"],
] as const;

export default function GuidePage() {
  return (
    <main id="main">
      <section className="guide-hero"><div className="container"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><Icon name="chevron" size={13} /><span aria-current="page">Getting started</span></nav><span className="eyebrow">LET’S GET COMFORTABLE</span><h1>Your first session,<br />one small step at a time.</h1><p>You don’t need a perfect gesture or technical experience. Find a comfortable position, allow yourself time, and start with a movement that feels repeatable.</p><div className="guide-hero-meta"><span><Icon name="windows" size={16} />Windows 10 / 11</span><span><Icon name="camera" size={16} />Webcam required</span><span>For version {RELEASE_VERSION}</span></div></div></section>
      <div className="container guide-layout">
        <aside className="guide-sidebar"><p>IN THIS GUIDE</p><nav aria-label="Guide sections">{sections.map(([id, title]) => <a href={`#${id}`} key={id}>{title}</a>)}</nav><Link href="/#download" className="button button-small"><Icon name="download" size={16} />Get the application</Link></aside>
        <div className="guide-content">
          <section id="before-you-start"><h2>A few things to have ready</h2><ul><li>A Windows 10 or 11 computer with a <strong>64-bit Intel or AMD processor</strong>.</li><li>A working built-in or USB webcam, with your face and any hand movements in view.</li><li>Comfortable, steady lighting and a position you can maintain without strain.</li><li>Time to experiment. Someone can help with downloading, permissions, and the first calibration if needed.</li></ul><p>The EXE includes the runtime and tracking models. You won’t need Node.js, additional development tools, an account, or an internet connection after the download.</p><div className="guide-callout"><Icon name="shield" /><div><h3>Know how to stop before you begin</h3><p>Live Control starts automatically once its camera is ready. Use <strong>Pause</strong> for a break, or <strong>Emergency stop</strong> to halt input. This shortcut works when the app is in the background, too:</p><div className="shortcut" aria-label="Control plus Shift plus X"><kbd>Ctrl</kbd><span>+</span><kbd>Shift</kbd><span>+</span><kbd>X</kbd></div></div></div></section>

          <section id="install"><h2>01. Choose your download</h2><p>Both files contain the same application. You only need one.</p><table className="comparison-table"><caption className="sr-only">Compare the two Windows downloads</caption><thead><tr><th scope="col">Installer</th><th scope="col">Portable</th></tr></thead><tbody><tr><td>Best for your everyday PC</td><td>Best when you prefer no installation</td></tr><tr><td>Run the setup and follow the prompts</td><td>Double-click the downloaded EXE</td></tr><tr><td>Adds desktop and Start menu shortcuts</td><td>Extracts its bundled files while running</td></tr><tr><td>Stores your profile on this PC</td><td>Also stores your profile on this PC</td></tr></tbody></table><div className="guide-actions"><a href={DOWNLOADS.setup} className="button"><Icon name="download" size={18} />Download installer</a><a href={DOWNLOADS.portable} className="button button-outline"><Icon name="download" size={18} />Download portable</a></div><div className="guide-callout warm"><Icon name="monitor" /><div><h3>If Windows displays a publisher message</h3><p>The current builds are unsigned. Verify that the file came from the <a href={`${REPOSITORY_URL}/releases/tag/assistive-control-1.0.1`} target="_blank" rel="noreferrer">project’s GitHub release</a> before deciding whether to continue. You do not need to switch off Windows security settings.</p></div></div></section>

          <section id="camera"><h2>02. Make room for your movement</h2><p>Place your webcam so it can see your face and the movements you want to try. If you plan to use hand movements, keep that hand inside the frame. Aim for even lighting rather than a bright window behind you.</p><ol><li>On Windows 11, open <strong>Settings → Privacy & security → Camera</strong>. On Windows 10, use <strong>Settings → Privacy → Camera</strong>.</li><li>Turn on camera access and allow desktop apps to access the camera.</li><li>Close another app if it is keeping your webcam busy.</li><li>Open Assistive Control and choose <strong>Calibrate</strong>.</li></ol><p>The home screen’s input banner should show <strong>REAL CONTROL ACTIVE</strong> when the native control module is available. This confirms the module loaded; it does not mean the app is already controlling the pointer from the home screen.</p><figure className="guide-figure"><Image src="/screenshots/home.png" alt="Assistive Control home screen showing the real input status and calibration and settings options." width={1200} height={820} sizes="(max-width: 900px) 95vw, 820px" /><figcaption>Actual application screenshot with an example saved profile. On a first launch, the button reads “Calibrate”.</figcaption></figure></section>

          <section id="calibrate"><h2>03. Find movements that feel repeatable</h2><p>Calibration starts with a short <strong>resting baseline</strong>. Relax in your normal position while the app observes what “at rest” looks like for you.</p><p>Then follow the on-screen prompts to try a movement you can perform comfortably. Repeat it when asked, and relax between repetitions. You can try more than one movement; the app compares the signals and keeps the stronger candidates.</p><ul><li>A face or hand movement can be a candidate. There is no required blink, smile, or fixed gesture.</li><li>Small, repeatable movements are more useful than straining for a large movement.</li><li>Results and available controls vary with the movements detected and the camera setup.</li><li>If the results do not feel right, adjust the lighting or position and recalibrate.</li></ul><p>Calibration saves a profile locally on that PC. A different person should create their own calibration rather than rely on someone else’s mapping.</p></section>

          <section id="personalize"><h2>04. Make the mapping your own</h2><p>From the home screen, open <strong>Settings</strong> after calibrating. Start with a comfortable cursor speed and sensitivity; higher values are not necessarily better.</p><figure className="guide-figure"><Image src="/screenshots/settings.png" alt="Actual settings screen with assisted switching selected and speed and sensitivity sliders." width={1200} height={820} sizes="(max-width: 900px) 95vw, 820px" /><figcaption>Settings with an example profile. Adjust one setting at a time so you can feel the difference.</figcaption></figure><h3>Review “Your controls”</h3><p>You can assign any calibrated movement to a pointer direction, a scroll direction, or a click or confirm action. Set a control to <strong>None</strong> if you don’t want an assignment.</p><p>Discrete actions also offer <strong>Once</strong>, <strong>Twice</strong>, and <strong>Hold</strong> patterns. For example, one reliable movement might trigger a left click once and a right click twice. That is an example, not a fixed gesture everyone must use.</p><figure className="guide-figure"><Image src="/screenshots/mapping.png" alt="The actual Your controls editor with movement assignments and once, twice, and hold patterns." width={1200} height={820} sizes="(max-width: 900px) 95vw, 820px" /><figcaption>Example assignments, captured from the app. Your movements and scores will be different.</figcaption></figure><h3>Choose how adaptation happens</h3><p><strong>Assisted</strong> switching asks before changing a movement and is the default. <strong>Automatic</strong> switching lets the app select a better available alternative when a control becomes unreliable. It does not create a new reliable movement if none was found.</p></section>

          <section id="start-control"><h2>05. Start, pause, and come back</h2><p>When you’re comfortable with the mapping, return home and choose <strong>Start</strong>. Live Control opens the camera and arms automatically when the camera is ready. Your mapped movements can then issue real input across your computer.</p><ul><li><strong>Pause</strong> halts input for a break. Use <strong>Resume</strong> when you’re ready.</li><li><strong>Emergency stop</strong> halts control. Use <strong>Re-arm</strong> only when ready to continue.</li><li><strong>Ctrl + Shift + X</strong> is the global emergency-stop shortcut.</li><li><strong>Recheck (adapt to now)</strong> captures a short new resting baseline when your position or resting movement changes.</li><li>Returning to the home screen disarms control. Tracking loss or low confidence also freezes input.</li></ul><p>Control can keep running while the app is minimized. Pause or stop it when you want to use another input method without movement control.</p></section>

          <section id="troubleshooting"><h2>If something doesn’t feel right</h2><div className="guide-trouble"><h3>The camera won’t start</h3><p>Check Windows camera permissions, close other camera apps, and make sure your webcam is connected. Restart Assistive Control after changing permissions.</p><h3>The banner says “Simulation mode”</h3><p>Real input is unavailable. Read the banner’s diagnostic message, confirm you’re using a supported Windows x64 PC, and try a fresh installer or portable download from the project release. A packaged installation should not require you to install npm packages manually.</p><h3>The pointer is hard to control</h3><p>Pause first. Reduce cursor speed or sensitivity in Settings, check your mapping, and recalibrate if the movements aren’t repeatable. Use Recheck when your resting position has changed.</p><h3>Hand tracking is unavailable</h3><p>The app can fall back to face-only tracking. Check the message in Live Control, keep your hand inside the camera frame, and use the complete release download, which includes the hand model.</p><h3>My control changed or became unreliable</h3><p>Use assisted switching if you want to review alternatives. Check your camera angle and lighting, or recalibrate. The app can only choose among reliable movements it has found.</p><h3>I need to report a problem</h3><p>Visit <a href={`${REPOSITORY_URL}/issues`} target="_blank" rel="noreferrer">GitHub issues</a> with your Windows version, which EXE you used, and the error text. Avoid including private camera footage or a personal calibration profile.</p></div></section>

          <section className="guide-next"><h2>Ready when you are.</h2><p>Start small, take breaks, and make the controls yours.</p><Link href="/#download" className="button">Choose your download <Icon name="arrow" size={18} /></Link></section>
        </div>
      </div>
    </main>
  );
}
